repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Get the latest version tag from Astral's repo
    rev: v0.15.16
    hooks:
      # Run the linter and auto-apply safe fixes
      - id: ruff-check
        args: [ --fix ]
      # Run the code formatter
      - id: ruff-format

